version: "3.3"
services:
    app:
        # build: .
        image: michaelscz/nedi:0.0.1
        user: "${UID}:${GID}"
        restart: unless-stopped
        ports: 
            - 8180:80
        volumes:
            - ./conf:/var/nedi/conf
        hostname: 'nedi'
        environment: 
            CRON: "15 * * * *"
        networks:
            - lan
    db:
        #image: mysql:8.0
        image: mariadb:10-focal
        user: "${UID}:${GID}"
        restart: unless-stopped
        command: 
            - --default-authentication-plugin=mysql_native_password
        volumes: 
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: dbpa55
        hostname: 'mariadb'
        networks:
            - lan
    adminer:
        image: adminer
        user: "${UID}:${GID}"
        restart: unless-stopped
        hostname: 'adminer'
        ports:
            - 8181:8080
        networks:
            - lan

networks:
    lan:

